[options]
csv_internal_sep = False
db_maxconn = 1000000
debug_mode = false
email_from = false
limit_memory_hard = 2684354560999
limit_memory_soft = 2684354560999
limit_request = 8192
limit_time_cpu = 600
limit_time_real = 55555
log_db = false
log_handler = [':INFO']
log_level = info
osv_memory_count_limit = false
smtp_password = false
smtp_port = 25
smtp_server = localhost
smtp_ssl = false
smtp_user = false
data_dir = /opt/odoo/datadir
http_port = 8069
unaccent = True
http_enable = True
limit_memory_soft_gevent = False
limit_memory_hard_gevent = False
addons_path=/opt/odoo/source_codes/odoo/addons,/opt/odoo/source_codes/dkm_odoo_saas_binary,/opt/odoo/source_codes/web

db_host = db
db_user = odoo
db_password = odoo
db_port = 5432
admin_passwd = qwufh38818901f23i

workers = 0
proxy_mode = False
;proxy_mode = True
;logfile = /opt/odoo/datadir/odoo.log

max_cron_threads = 2
list_db = true
db_name = saas_kit_trial_19_1

server_wide_modules = web,base
dev_mode=xml
disable_auto_upgrade_modules=True
